use_frameworks!

platform :ios, '8.0'

target 'FakeTalkingdataAnalytics_Example' do
  pod 'FakeTalkingdataAnalytics', :path => '../'

  target 'FakeTalkingdataAnalytics_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
